# Java 17 image
FROM tomcat:9.0-jdk17

# Remove default ROOT app
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your WAR file to tomcat
COPY target/QueryResolvingSystem.war /usr/local/tomcat/webapps/ROOT.war

# Expose port
EXPOSE 8080

# Start tomcat
CMD ["catalina.sh", "run"]
